[package]
name = "kalmarity-control"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger      = "0.10"
log             = "0.4.17"
anyhow          = "1"
#futures         = "0.3"
clap            = "3"

[dependencies.tokio]
version = "1.28.0"
features = ["rt-multi-thread", "signal", "parking_lot", "macros", "fs"]

[dependencies.rdkafka]
version = "0.29"
features = ["dynamic-linking", "tokio"]
